# Generated by Django 5.1.4 on 2025-04-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Chờ giao hàng'), ('delivered', 'Đã giao hàng'), ('review', 'Đánh giá')], default='pending', max_length=10),
        ),
    ]
