# Generated by Django 5.1.4 on 2025-04-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_delivery_date_order_delivery_time_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_auto_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
