# Generated by Django 5.1.4 on 2025-04-16 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_review_product_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('review', 'Đã đánh giá')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.order'),
        ),
    ]
