name: Django Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ecommerce .

      - name: Deploy to Render
        if: success()
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"